exchange_rates = [
    {"base_currency": "USD", "target_currency": "EUR", "rate": 0.86},
    {"base_currency": "USD", "target_currency": "GBP", "rate": 0.75},
    {"base_currency": "USD", "target_currency": "JPY", "rate": 109.63},
    {"base_currency": "USD", "target_currency": "AUD", "rate": 1.32},
    {"base_currency": "USD", "target_currency": "CAD", "rate": 1.26},
    {"base_currency": "USD", "target_currency": "CHF", "rate": 0.92},
    {"base_currency": "USD", "target_currency": "CNY", "rate": 6.48},
    {"base_currency": "USD", "target_currency": "INR", "rate": 74.82},
    {"base_currency": "USD", "target_currency": "BRL", "rate": 5.23},
    {"base_currency": "EUR", "target_currency": "USD", "rate": 1.16},
    {"base_currency": "EUR", "target_currency": "GBP", "rate": 0.87},
    {"base_currency": "EUR", "target_currency": "JPY", "rate": 133.53},
    {"base_currency": "EUR", "target_currency": "AUD", "rate": 1.54},
    {"base_currency": "EUR", "target_currency": "CAD", "rate": 1.47},
    {"base_currency": "EUR", "target_currency": "CHF", "rate": 1.07},
    {"base_currency": "EUR", "target_currency": "CNY", "rate": 7.56},
    {"base_currency": "EUR", "target_currency": "INR", "rate": 86.91},
    {"base_currency": "EUR", "target_currency": "BRL", "rate": 6.03},
    {"base_currency": "GBP", "target_currency": "USD", "rate": 1.34},
    {"base_currency": "GBP", "target_currency": "EUR", "rate": 1.15},
    {"base_currency": "GBP", "target_currency": "JPY", "rate": 149.83},
    {"base_currency": "GBP", "target_currency": "AUD", "rate": 1.73},
    {"base_currency": "GBP", "target_currency": "CAD", "rate": 1.65},
    {"base_currency": "GBP", "target_currency": "CHF", "rate": 1.20},
    {"base_currency": "GBP", "target_currency": "CNY", "rate": 8.48},
    {"base_currency": "GBP", "target_currency": "INR", "rate": 97.31},
    {"base_currency": "GBP", "target_currency": "BRL", "rate": 6.75},

]
